### ISSUE TITLE
Create login screen 

### ISSUE THREAD

**Issue by somi6k** [InterviewMe/interviewme#1]
Allow users to sign up and register in Parse

**Comment by codepathreview** [comment]
Looks like you are missing the following required user story:

- Update group info (2pts)

Your group milestone is incomplete until all the [required user stories] are complete.

Whenever you make updates to your project that require re-grading, you need to re-submit your project using the submit button on the associated group milestone page in the course portal. This will flag your project as “updated” on our end and we know to re-grade. 
/cc @codepathreview

**Comment by codepathreview** [comment]
Looks like you are missing the following required user story:

- Complete ALL of the optional stories (2pts)

Your group milestone is incomplete until all the [required user stories] are complete.

Whenever you make updates to your project that require re-grading, you need to re-submit your project using the submit button on the associated group milestone page in the course portal. This will flag your project as “updated” on our end and we know to re-grade. 
/cc @codepathreview
